### ISSUE TITLE
Incompartibility with Foreman 1.18

### ISSUE THREAD

**Issue by prokhorovva** [ATIX-AG/foreman_scc_manager#15]
Hi.
Since APIv1 dropped in the Foreman version 1.18 the plugin became unusable.

> APIv1 has been deprecated since Foreman 1.9 and Foreman 1.17 is the last version supporting APIv1. We strongly recommend moving to v2 if you are still using v1.

**Comment by mdellweg** [comment]
I do not think, this plugin uses any API (neither v1 nor v2), which is a shame on another level. But it means that that cannot be the problem you are experiencing. Can you elaborate a little bit more? What Version are you using (latest tag, or master)? What is the error you are seeing?

**Comment by prokhorovva** [comment]
Version 1.3.1 from git, also package 1.3.1 from foreman-plugins^
```
2018-08-06T14:20:12 [F|app|] <NameError> uninitialized constant Api::TaxonomyScope
        /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/foreman_scc_manager-1.3.1/app/controllers/scc_accounts_controller.rb:4:in `<class:SccAccountsController>'
        /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/foreman_scc_manager-1.3.1/app/controllers/scc_accounts_controller.rb:1:in `<top (required)>'
        /opt/rh/rh-ruby24/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        /opt/rh/rh-ruby24/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        /opt/theforeman/tfm/root/usr/share/gems/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        /opt/theforeman/tfm-ror51/root/usr/share/gems/gems/activesupport-5.1.6/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
        /opt/theforeman/tfm-ror51/root/usr/share/gems/gems/activesupport-5.1.6/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
        /opt/theforeman/tfm-ror51/root/usr/share/gems/gems/activesupport-5.1.6/lib/active_support/dependencies/interlock.rb:11:in `loading'
        /opt/theforeman/tfm-ror51/root/usr/share/gems/gems/railties-5.1.6/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'

```

**Comment by mdellweg** [comment]
Seems like removing the TaxonomyScope lines from the controller fixes the issue.
